name       : perl-params-validationcompiler
version    : '0.27'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.27.tar.gz : 50a99968359d430e34ea8a12e7f08a669ffd34a3dae4d8ea9ca076c1100af9b2
license    : Artistic-2.0
component  : programming.perl
summary    : Build an optimized subroutine parameter validator once, use it forever
description: |
    Build an optimized subroutine parameter validator once, use it forever
builddeps  :
    - perl-class-data-inheritable
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-exception-class
    - perl-importer
    - perl-mro-compat
    - perl-role-tiny
    - perl-specio-exporter
    - perl-sub-info
    - perl-term-table
    - perl-test2-plugin-nowarnings
    - perl-test2-suite
    - perl-test-simple
    - perl-test-without-module
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
