name       : perl-params-validationcompiler
version    : '0.31'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.31.tar.gz : 7b6497173f1b6adb29f5d51d8cf9ec36d2f1219412b4b2410e9d77a901e84a6d
homepage   : https://metacpan.org/pod/Params::ValidationCompiler
license    : Artistic-2.0
component  : programming.perl
summary    : Build an optimized subroutine parameter validator once, use it forever
description: |
    Build an optimized subroutine parameter validator once, use it forever
builddeps  :
    - perl-eval-closure
    - perl-exception-class
    - perl-specio-exporter
    - perl-test2-plugin-nowarnings
    - perl-test2-suite
    - perl-test-without-module
rundeps    :
    - perl-eval-closure
    - perl-exception-class
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
