name       : perl-params-validationcompiler
version    : 0.24
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.24.tar.gz : a8963747bae618c2b96ec1918ef2b6ea7dd7ff3dbcebc9de6124b2771a4f4287
license    : Artistic-2.0
component  : programming.perl
summary    : Build an optimized subroutine parameter validator once, use it forever
description: |
    Build an optimized subroutine parameter validator once, use it forever
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
